### ISSUE TITLE
Ik wil toegang!

### ISSUE THREAD

**Issue by larixk** [grrr-amsterdam/classifier-prototype#1]

**Comment by harmenjanssen** [comment]
David is de overlord van onze repo's, mijn handen zijn gebonden!

**Comment by aapit** [comment]
Ik lees het nu pas, maar wil toch nog even kwijt dat Harmen wat overdrijft. Hij zit namelijk in de 'admins'-groep, samen met Mattijs en mij :)

**Comment by harmenjanssen** [comment]
Ja, ik kon nergens een 'invite user' of iets dergelijks vinden!
Moet je me maar eens laten zien ;)

Harmen Janssen

Op 10 april 2015 19:35 schreef David Spreekmeester <notifications@github.com

**Comment by aapit** [comment]
Gewoon onder Settings / Collaborators, daar kun je de 'Devs' en 'Admins'
groepen eraan hangen.

David ¦ Grrr
